### ISSUE TITLE
Finally figured out geofire

### ISSUE THREAD

**Issue by daveozoalor** [firebase/geofire-js#100]
After the debacle the other day, I finally figured out how to implement geofire with firebase.
Special thanks to the guy who linked me to muni.

It wasn't enough, but it sure helped a great deal. Now, I'm going to do a PR on the documentation. 
On the other hand, The html5Geolocation example should contain a section to retrieve the location of the user.
The muni example, should include a section to upload the geolocation co ordinates of the vehicles, somehow. 
Those were the sections that would have made life easier.

**Comment by jwngr** [comment]
Thanks. I'll review your PR if you send it my way.

Note that the MUNI example is going away with https://github.com/firebase/geofire-js/pull/99 because the Open Data Set we used for the buses is not longer supported. So I wouldn't waste any time updating that example.
