### ISSUE TITLE
geofire breaks with latest Firebase

### ISSUE THREAD

**Issue by Nostrus** [firebase/geofire-js#101]
After upgrading to Firebase 3.0.0, `locationDataSnapshot.key()` calls fail in Geofire, because they should be `locationDataSnapshot.key` according to Firebase's new API.

**Comment by jwngr** [comment]
Yup, we need to do some work to upgrade to the latest version since `3.0.0` introduced some breaking changes. Follow #99 for updates. Closing this since we will just track it there.

**Comment by Nostrus** [comment]
Can't wait, thanks for quick reply :)

**Comment by jwngr** [comment]
Version `4.1.0` of GeoFire for JavaScript has just been release! Check out the change log [here](https://github.com/firebase/geofire-js/releases/tag/v4.1.0). It supports `^2.4.0 || 3.x.x` so feel free to use it with either the old or the new SDK!

**Comment by Nostrus** [comment]
Great news, seems to work fine so far :)
