### ISSUE TITLE
Geo messages

### ISSUE THREAD

**Issue by cpsiaki** [firebase/geofire-js#104]
Hi everyone. Is there a way to query geofire by proximity as well as date?

I've got an app writing messages to firebase and I use the message key to save the messages location with geofire. I want to query these messages based on proximity to my current location but also get messages in date order (recent first, descending). Is this even possible with GeoFire?

Should I integrate the app with a Parse/FB combo?

Thanks in advance for any help on this issue :)

**Comment by jwngr** [comment]
The underlying Firebase SDK only currently supports queries along one dimension, so you won't be able to do this with a single server side query. I would suggest doing a geo query and then filtering by date client-side. Alternatively, you can set up multiple GeoFire indexes (say, one for each day) and only query the one you care about.

**Comment by cpsiaki** [comment]
Thanks for the answer, I'll try an index on the day, maybe the hour... that could be overkill.

**Comment by jwngr** [comment]
It could be overkill depending on your use case, but it should scale fine in terms of the Firebase realtime database. Good luck!
