### ISSUE TITLE
GeoFire updateCriteria not working

### ISSUE THREAD

**Issue by jlsuarezs** [firebase/geofire-js#110]
Hi Guys,

Thank you for this amazing library.

Well, I am having one problem when I try to updateCriteria using the center of the map coordinates as a criteria and a radius of 3km.

Geoquery is keeping the same values and its not updating.

For example,

The center of the map is -36.53258538080384,174.57454663819414 and my object is at -37.7861473057771,175.2801817564063 (152.59km) and its still on the map.

Any help, please?

**Comment by jdimond** [comment]
Can you confirm you are listening to key exited events (see https://github.com/firebase/geofire-js/blob/master/docs/reference.md#geoqueryoneventtype-callback). If you are, can you please provide a minimal example with code that reproduces this issue? Thanks.

**Comment by jwngr** [comment]
Please follow the new issue template. Feel free to open a new issue with a full repro and version information.
