### ISSUE TITLE
Canceling "updateCriteria" query before the ready event throws an error

### ISSUE THREAD

**Issue by u5bob** [firebase/geofire-js#124]
### Version info

**Firebase:** 3.1.0-rc.3

**GeoFire:** 4.1.1

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case
https://jsfiddle.net/u5bob/242jjbdo/

[geofire_bug.zip (json)](https://github.com/firebase/geofire-js/files/507497/geofire_bug.zip)

### Steps to reproduce

1. Create a new query.
2. After the ready event update the query criteria (with a wider radius for example)
3. Cancel the query while it's still in progress (before the ready event fires)
4. Notice: "TypeError: Cannot read property 'isInQuery' of undefined" thrown in the console

### Expected behavior

Should cancel the updated query with no errors

### Actual behavior

Canceling "updateCriteria" query before the ready event throws an error

**Comment by jwngr** [comment]
Thanks for reporting this @u5bob! Sorry I hadn't looked into it yet. The repro was super helpful and I was able to put together a small fix in #125. I'll cut a new patch release after that gets merged in.

**Comment by jwngr** [comment]
[GeoFire `4.1.2`](https://github.com/firebase/geofire-js/releases/tag/v4.1.2) was just released with a fix for this issue. Thanks again for reporting it!
