### ISSUE TITLE
Does GeoFire work with Admin-SDK?

### ISSUE THREAD

**Issue by christopherlo93** [firebase/geofire-js#128]
I am using a node.js server to handle push notifications. I would like to geotarget notifications, I was wondering if GeoFire is working with the Firebase-admin SDK. It doesn't seem to be working with it.

**Comment by jwngr** [comment]
Yes, this repo should work just fine with the Firebase Admin Node.js SDK. If you are having an issue or seeing an error, please open up a new issue which follows the full issue template, including version information as well as a repro.
