### ISSUE TITLE
Possible Unhandled Promise Rejection?

### ISSUE THREAD

**Issue by agumack** [firebase/geofire-js#135]
Hi guys, 

I have use geofire with react-native.
i have one error message "Possible Unhandled Promise Rejection" when call:
```
var geoFire = firebaseApp.geoInit("fanpages-geo"); //new GeoFire(firebaseApp.database.ref("fanpages-geo"));
        var geoQuery = geoFire.query({
            center: [11.933333, 108.450000],
            radius: 10.5
        });

        var onReadyRegistration = geoQuery.on("ready", function () {
            console.log("GeoQuery has loaded and fired all other events for initial data");
        });
```

Thanks for support!

**Comment by jwngr** [comment]
Can you please fill out the issue template so I know what versions of each library (Firebase, GeoFire, React Native) you are using?

**Comment by agumack** [comment]
Hi @jwngr 
Thank you for reply. 
I am using:
"react-native": "0.37" 
"firebase": "^3.6.8",
"geofire": "^4.1.2",

This is screenshot:
<img width="821" alt="screen shot 2017-02-13 at 9 12 44 am" src="https://cloud.githubusercontent.com/assets/19372005/22868871/1a6e03c2-f1cd-11e6-9c81-bac1cf7de14e.png">

Logs:

<img width="530" alt="screen shot 2017-02-13 at 9 12 56 am" src="https://cloud.githubusercontent.com/assets/19372005/22868879/247d9daa-f1cd-11e6-97f0-2392e4ee92d6.png">

**Comment by agumack** [comment]
this is error when I integration "react-native-firestack"
I remove react-native-firestack and working now. 
Thanks for support!

**Comment by jwngr** [comment]
Sounds like that library is the one with the issues then. Thanks for the report.
