### ISSUE TITLE
geoFire.query not working with big radius

### ISSUE THREAD

**Issue by jsappme** [firebase/geofire-js#144]
### Version info

**Firebase:*** ^3.6.9
**GeoGire:** ^4.1.2
**Node.js:** 6.10.0

The following code works well with small radius search but when retrieving bigger radius, it does not work anymore. Any idea why?

```
getGeoQueryOffers(lat, long, radius) {
    const geoFire = new GeoFire(this.db.ref(config.db_offer_locations))
    return geoFire.query({
      center: [lat, long],
      radius: radius
    })
  }

let offers = []
const geoQuery = db.getGeoQueryOffers(user.geolocation.l[0], user.geolocation.l[1], config.search_radius)

geoQuery.on('key_entered', (key, location, distance) => {
    const offer = db.getOffer(key)
    offers.push(offer)
  })

  geoQuery.on('ready', () => {
    const radius = geoQuery.radius()
    console.log("RADIUS: " + radius)
    geoQuery.cancel()
    co(function *(){
      let results = yield offers
      results.sort((a, b) => b.createdAt - a.createdAt)
      console.log("offers_count: " + results.length)
      if(results.length) {
        yield bot.sendPreSetText(recipient, user.language, "result_count", results.length)
      }
      else {
        yield bot.sendPreSetText(recipient, user.language, "no_result")
      }
```
### Expected behavior

retrieve all geolocations on earth

### Actual behavior

0 result

**Comment by jwngr** [comment]
I can't say for sure why it doesn't work, but we have gotten similar reports for the other GeoFire libraries:
  * https://github.com/firebase/geofire-java/issues/46
  * https://github.com/firebase/geofire-objc/issues/64
  * https://github.com/firebase/geofire-objc/issues/27

In general, this library is not really mean to be used with a radius that is the size of the whole world. At that point, the library does not really become useful. I would suggest simply bounding the maximum size of the query and, if you want to, for example, list all keys in a certain continent, just store all those keys under that continent and retrieve them in a different way.

If you are able to put together an actual reproduction of this issue (in JSFiddle or Plunker) and explain the exact steps to get the behavior you are seeing, hopefully someone can debug it and put together a PR to fix the issue. For now though, I am going to close this as won't fix as I think it is not really a use case we are aiming to handle.

**Comment by enjoiful** [comment]
Any ideas for what accuracy we expect to work?
