### ISSUE TITLE
Node.js: "ReferenceError: GeoFire is not defined"

### ISSUE THREAD

**Issue by DanJayF** [firebase/geofire-js#145]
So i'm trying to build a simple Admin panel for my app using Node.js Express and the Firebase Admin SDK.

I'm attempting to use the GeoFire.set() method to simply process a form and add new entries to my database but unfortunately JS is not my strong point.

I've initialized my app with:
```
var admin = require("firebase-admin");
var serviceAccount = require("path/to/credentials.json");
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "https://------.firebaseio.com",
});
```
I have a reference to my database as follows:
```
var fbDatabase = admin.database();
var listRef = fbDatabase.ref();
```
But when I go to instantiate GeoFire, I get a ReferenceError like this:
```
var geoFire = new GeoFire(listRef);
                  ^
ReferenceError: GeoFire is not defined
```

I have not used a require('geofire') in this app.js file as I'm unsure if it is even required. The docs don't mention anything about inserting a require, and since I'm instantiating a new GeoFire instance anyway, I didn't think it's needed. It doesn't make a difference anyway however if i add it.
Firebase Admin and GeoFire are definitely installed and up to date.

This seems to me like something simple I'm missing, would anyone with more experience be able to help? Thanks.

### Version info
**Firebase:** v3.8.0
**GeoFire:** v4.1.2
**Other:**
Node.js v 6.10.2
Express 4.15.2
Chrome 58.0.3029.81 beta
PhpStorm 2017.1.2

**Comment by Woodyjl** [comment]
@DanJayF place
 var GeoFire = require('geofire');

before
var geoFire = new GeoFire(listRef);

**Comment by DanJayF** [comment]
I'm super late replying too but just thought I'd close this out.
I've since switched to using Firebase's Web SDK instead of Admin as I built a React web app in the end. This in turn meant I used ES6, so I'm importing instead of requiring the GeoFire library. I think this may have also been the issue before, coming from PHP I was a Node newbie this time last year 😉.
Thanks @Woodyjl
