### ISSUE TITLE
get all key with ready geofire query

### ISSUE THREAD

**Issue by mohamedtijani** [firebase/geofire-js#146]
in my firebase database i'm registered many location with an Reactjs application.
And I have a mobile application with React Native and I want to recover the keys following a geofire request in my componentWilMount()
But I could not retrieve them 

const geofire = require('geofire');

componentWillMount() {
       const geofireRef = new geofire(get('locations'));

     let geoQuery = geofireRef.query({
         center: [23.581395, 58.408548],
        radius: 200
      });

     let onKeyEnteredRegistration  = geoQuery.on("ready", () => {

     });
    alert(JSON.stringify(onKeyEnteredRegistration));
  }

**Comment by skhiearth** [comment]
The circle query would only return keys that are within a 200km radius.

**Comment by RadiBarq** [comment]
if you want to get the keys within a radius the code should look like this

geoQuery.on("key_entered", function (key, location, distance) {
/// store the keys in an array or what ever
}

**Comment by puf** [comment]
Looks like this one was [answered](https://github.com/firebase/geofire-js/issues/146#issuecomment-404766155) by @RadiBarq, so I'm gonna close it since I'm cleaning up old issues.
