### ISSUE TITLE
Feature Request:  C# implementation for Unity

### ISSUE THREAD

**Issue by agentargyle** [firebase/geofire-js#150]
Firebase itself has great c# support for Unity. Too bad GeoFire is not there yet. Unity supports Javascript to a degree, so this may work. However, C# would be preferable for many Unity devs. 
Just think of all the game devs out there trying to build the next Pokemon Go... 

Thanks!

**Comment by MauricioJuanes** [comment]
Has anyone tried to use the JS version with unity?

**Comment by agentargyle** [comment]
I have not but now there is this: https://assetstore.unity.com/packages/tools/integration/geofire-for-unity-106839 so figure that is the way to go since Unity seems to be deprecating their version of JS anyway- at least that is what I heard through the grapevine.

**Comment by puf** [comment]
*Cleaning up old issues*

There's not much we can do about this feature request in this repo. If you still think it would be useful to have a geofire-csharp/geofire-unity variation of this library, [file a feature request](https://firebase.google.com/support/contact/bugs-features/) with our support team.
