### ISSUE TITLE
How can I off the event listner

### ISSUE THREAD

**Issue by abhitheawesomecoder** [firebase/geofire-js#153]
I am using code like this in react native and its working fine 

this.geoRef = geoQuery.on('key_entered', async (uid, location, distance) => {
      console.log(uid + ' at ' + location + ' is ' + distance + 'km from the center')  
    })

But how can i off the listener, something like this, when component unmounts ?

  componentWillUnmount() {
    this.geoRef .off('key_entered')
}

**Comment by BuffMcBigHuge** [comment]
`this.geoRef.cancel()`
