### ISSUE TITLE
Is Firebase 4.x.x supported?

### ISSUE THREAD

**Issue by eightyfive** [firebase/geofire-js#156]
### Version info

**Firebase:**
^4.1.3

**GeoFire:**
^4.1.2

### Test case

I am using geofire latest with firebase 4.x.x and it _seems_ to work, although the firebase peer dependency listed version is lower: `^2.4.0 || 3.x.x`.

So my question is: Is Firebase 4.* officially supported?

### Steps to reproduce

1. Run `npm ls`
2. Error in terminal: `npm ERR! peer dep missing: firebase@^2.4.0 || 3.x.x, required by geofire@4.1.2`

### Expected behavior

No warning/error in terminal.

### Actual behavior

Warning/error in terminal.

**Comment by MichaelSolati** [comment]
I've used Geofire with Firebase 4 with no issues what so ever, seriously, I'd say yes it's supported (even though the peer dependency hasn't been updated to reflect that).

**Comment by jfbourne** [comment]
Same concern here but will give it a shot.

**Comment by mcdonamp** [comment]
Thanks for checking, in the future feel free to submit a PR to fix it and we're happy to merge!
