### ISSUE TITLE
GeoFire is being abandoned?

### ISSUE THREAD

**Issue by wmonecke** [firebase/geofire-js#158]
Is GeoFire still being mantained? I just feel like by looking at the PR's and the updates that this awesome feature is being slowly faded out... If so, could you please confirm so that we do not use it in long-term projects.

Thank you!

**Comment by wbattel4607** [comment]
In Google's release of Firestore, they noted that they have pulled the engineers from Geofire away to work on the GeoPoint architecture for Firestore.

I do not know if they plan to return to Geofire, but that explains why they've been quiet the past few months.

**Comment by alxvallejo** [comment]
@wmonecke @wbattel4607  What would you suggest as an alternative for non Firestore (ie Firebase) projects then? I'm surprised this isn't being maintained.

**Comment by wbattel4607** [comment]
@alxvallejo we've taken a gamble and are using Geofire still. Eventually, if/when we migrate to Firestore, we  shouldn't need it anymore because Firestore has its own GeoPoint architecture.

**Comment by khandelwalManish** [comment]
I am facing issue in gradle build.

**Comment by sebastianovide** [comment]
we are using Geofire in an old project. Geofire is blocked to 4.1.2 which depends on firebase 3.9.0. Not sure what is after that version (4.12.0) but I guess that there are few bug fixes among other things. So, if geofire is not being updated, we are stuck in an old version of firebase. 

Any ideas ?

**Comment by wbattel4607** [comment]
Looks like geofire might finally be getting some love. New activity on this repo from the Firebase team in the last 24 hours.

Thanks @mcdonamp :)

**Comment by sebastianovide** [comment]
I see https://github.com/firebase/geofire-js/pull/172. 

Our project using Geofire cannot change password anymore as firebase 3.9 is throwing errors doint a POST call. Something must have change in firebase. (just when I was nearly convincing my team how mature Firebase was...)

@mcdonamp is there any plans to finishe that PR? We really cannot remove Geofire at this stage.

**Comment by mcdonamp** [comment]
I think that #169 is long term fix to this (thanks to @MichaelSolati!)

@sebastianovide, have you [migrated your project to firebase.google.com](https://firebase.google.com/support/guides/firebase-web)? If you're still using the legacy auth (which I believe is being turned down), you'll start getting errors.

If that's not the case, mind posting the error for me to help with?

**Comment by mcdonamp** [comment]
Do you access the project on firebase.com or firebase.google.com? Given that project number, I assume you're on firebase.google.com. Mind letting me know what the error is?

**Comment by sebastianovide** [comment]
firebase.google.com.
using an updatePassword I get a 400 error from firebase.js:95 (POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/setAccountInfo?key=xxxxxxx)

**Comment by mcdonamp** [comment]
Is there a message in the error?

**Comment by sebastianovide** [comment]
great... thank ! going to the basic solved the problem... it was a simple as "This operation is sensitive and requires recent authentication. Log in again before retrying this request." .... never trust old code written by others !

thanks @mcdonamp 

is there anything important in firebase.js after 3.9 that we should be concerned about ?

**Comment by mcdonamp** [comment]
The full release notes are here: https://firebase.google.com/support/release-notes/js, unsure what exactly you're relying on so I don't know what will/won't be relevant for you. Glad things are working again though :)

In the future, https://firebase.google.com/support/contact/troubleshooting/ is going to be a good resource for this type of help.

**Comment by puf** [comment]
*Cleaning up old issues*

It looks like no further action is required here. If a similar concern pops up going forward, please open a new issue.
