### ISSUE TITLE
Firebase Cloud Firestore

### ISSUE THREAD

**Issue by vascoV** [firebase/geofire-js#163]
Geofire is an amazing library that can be used with the FIrebase Real-time Database, 
is gonna be updated for the Cloud Firestore?

**Comment by sonaye** [comment]
You can utilize geohashes.

```javascript
import g from 'ngeohash';

const store = firestore();

const addLocation = (lat, lng) =>
  store
    .collection('locations')
    .add({
      g10: g.encode_int(lat, lng, 24), // 10 km
      g5: g.encode_int(lat, lng, 26), // 5 km
      g1: g.encode_int(lat, lng, 30) // 1 km
      // more options here https://github.com/yinqiwen/ardb/wiki/Spatial-Index#search
    });

const nearbyLocationsRef = (lat, lng, d = 1) => {
  const h = g.encode_int(lat, lng, d === 10 ? 24 : d === 5 ? 26 : 30);

  return store
    .collection('locations')
    .where(`g${d}`, '>=', g.neighbor_int(h, [-1, -1]))
    .where(`g${d}`, '<=', g.neighbor_int(h, [1, 1]));
};
```

**Comment by MichaelSolati** [comment]
To those who care, I had a PR for Firestore support but after a little conversation it was deemed not to be the appropriate time to bring it into the official library. However for any of you that are interested I have my `geofirestore` library code [available here](https://github.com/MichaelSolati/geofirestore), and on npm `npm i geofirestore`. It works very effectively the same as the official `geofire` library (same class names/functions/etc...)

**Comment by zoro238** [comment]
pls for android java

**Comment by puf** [comment]
We split the GeoFire libraries into two:

1. A core GeoFireUtils library with just the bits having to do with geohashes and queries
2. The complete library that implements #1 on top of Realtime Database

For documentation on how to use #1 with Cloud Firestore, see the documentation here: https://firebase.google.com/docs/firestore/solutions/geoqueries
