### ISSUE TITLE
Is it possible to switch the format of location to become [longitude, latitude] ?

### ISSUE THREAD

**Issue by ghost** [firebase/geofire-js#166]
In this module, locations must have the form [latitude, longitude]. I am not sure whether this is required by firebase. Currently, my project uses Firebase for real time stuff while MongoDB works for permanent, or long term, data storing. In MongoDB, it has a data type called Geospatial which helps to store location in [longitude, latitude] form.

Perhaps, this suggestion is just for my own good. If most of database platform are storing [latitude, longitude] as the location data and MongoDB is just a special case, I think it is okay. If not, which means most of them are using [longitude, latitude], I suggest to change it back to [longitude, latitude].

Just want to raise a concern about the format of location to match the format of other database, or stuff.

Thanks.

**Comment by wbattel4607** [comment]
Strange. MDB is the first time I've seen Long/Lat used. Otherwise it tends to be exclusively Lat/Long.

I'd just use a helper function to convert whenever you have to interact with Mongo.

This is interesting: https://stackoverflow.com/a/18721489/8606106
It suggests that Long/Lat makes more sense mathematically but Lat/Long is what made sense historically.

**Comment by MichaelSolati** [comment]
I don't think it's reasonable to expect the package to do reverse coordinates. The only reason why Mongo does it because it uses GeoJSON Points for their queries; while geofire uses geohashes.

**Comment by puf** [comment]
*Cleaning up old issues*

Lat/Lon is most idiomatic, which is why we chose it for GeoFire. At this point there is no compelling reason to change that. Given the lack of activity on this thread, I'm going to close it for now.
