### ISSUE TITLE
can't catch() / suppress exceptions

### ISSUE THREAD

**Issue by theprojectsomething** [firebase/geofire-js#168]
It seems to be difficult to catch and or suppress exceptions when setting a location.

Is a promise being returned if a validation exception is thrown prior to the firebase logic?

Example code:
```javascript
// set an invalid latlng
geofire.set('key', [123, 456])
.then(() => console.log('how did that happen?'),

// standard error as per the docs - doesn't fire
() => console.log(`documented error: ${e.message}`))

// undocumented but standard stuff - doesn't fire
.catch(e => console.log(`undocumented error: ${e.message}`));
```
^ above seems to throw a standard exception and terminate.
```sh
error: Error: Invalid GeoFire location '123,456': latitude must be within the range [-90, 90]
    at validateLocation (/node_modules/geofire/dist/geofire.js:287:11)
    at /node_modules/geofire/dist/geofire.js:102:9
    at Array.forEach (native)
    at GeoFire.set (/functions/node_modules/geofire/dist/geofire.js:94:28)
    at Object.myfunc (/myfunc.js:1:18)
    at <anonymous>
```

**Comment by MichaelSolati** [comment]
A promise is only returned IF it passes validation. The function validates THEN inserts the data into Firebase (returning the `set` which returns a promise). That could be changed though...

**Comment by puf** [comment]
The comment by @MichaelSolati seems to answer this question. Closing for now, as I'm cleaning up old issues with no clear AI.
