### ISSUE TITLE
Angular 6 - Error while creating an instance of GeoFire

### ISSUE THREAD

**Issue by ravivit9** [firebase/geofire-js#173]
### Version info

**Firebase:**
^4.12.1
**GeoFire:**
^4.1.2

**Other (e.g. Node, browser, operating system) (if applicable):**
        "agm/core": "^1.0.0-beta.2",
        "angular/animations": "^6.0.0",
        "angular/cdk": "^6.0.0",
        "angular/common": "^6.0.0",
        "angular/compiler": "^6.0.0",
        "angular/core": "^6.0.0",
        "angular/forms": "^6.0.0",
        "angular/http": "^6.0.0",
        "angular/material": "^6.0.0",
        "angular/platform-browser": "^6.0.0",
        "angular/platform-browser-dynamic": "^6.0.0",
        "angular/router": "^6.0.0",
        "fortawesome/fontawesome": "^1.1.7",
        "ng-select/ng-select": "^1.4.0",
        "ngrx/effects": "^5.2.0",
        "ngrx/store": "^5.2.0",
        "angularfire2": "^5.0.0-rc.6.0",
        "bootstrap": "^4.1.0",
        "cordova-android": "^7.1.0",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-geolocation": "~4.0.1",
        "core-js": "^2.5.5",
        "firebase": "^4.12.1",
        "font-awesome": "^4.7.0",
        "geofire": "^4.1.2",
        "hammerjs": "^2.0.8",
        "mt-latlon": "^0.1.1",
        "rxjs": ">=5.6.0-forward-compat.4",
        "rxjs-compat": "^6.1.0",
        "uuid": "^3.2.1",
        "web-animations-js": "^2.3.1",
        "zone.js": "0.8.26"

### Steps to reproduce

import { Injectable, NgZone } from '@angular/core';
import { AngularFireDatabase } from 'angularfire2/database';
import { GoogleMapsAPIWrapper } from '@agm/core';
import { MapsAPILoader } from '@agm/core';
import * as GeoFire from 'geofire';

@Injectable()
export class GeoService  extends GoogleMapsAPIWrapper {
  dbRef: any;
  geoFire: any;

  constructor(private db: AngularFireDatabase, private auth: AuthService) {
    const path = this.getDBRef(this.vehicleType);
    this.dbRef = this.db.list(path);
    **this.geoFire = new GeoFire(this.dbRef.$ref);**
}

  getDBRef = (type) => {
    const country = (this.auth.userInfo.country ? this.auth.userInfo.country : 'India');
    const returnDBRef = `${country}/${type.toLowerCase()}`;
    return returnDBRef;
  };

}

### Expected behavior
The geoFire instance should be created

### Actual behavior
Runtime error while creating the following:
    this.geoFire = new GeoFire(this.dbRef.$ref);

**Comment by MichaelSolati** [comment]
Yup, I had this issue over the weekend. This may be resolved with a PR that's in the works (I tested it with #169 )

**Comment by ravivit9** [comment]
@MichaelSolati , thanks for all of you guys for your best efforts to bring back GeoFire to life again.  Any timeline you are expecting the A6 compatible version of GeoFire?

Once again thanks for all the efforts.

**Comment by MichaelSolati** [comment]
@ravivit9 ooh, I can't really say. Quality code is obviously very important to them, so the PR will have to be ripped apart and judged. But if you reach out to me via email (my email is on my profile), I can help you out until an official fix is merged in.

**Comment by tombalcaen** [comment]
I'm having the same issue. Thanks for all the efforts solving this.

**Comment by daveparks23** [comment]
Any update on how to move forward with GeoFire and Angular 6  Thanks!

**Comment by nicolas-saldarriaga** [comment]
I have the same issue with "firebase": "^5.1.0" and "geofire": "^4.1.2" in the following line: this.geoFire = new GeoFire(this.dbRef.query.ref);

**Comment by nicolas-saldarriaga** [comment]
any update?

**Comment by nfoote** [comment]
I would also be very grateful for some updates on this. I'm having the same issue described above. Using "firebase": "^5.0.3" with"geofire@^4.1.2" and getting the following error:

[<a href="https://ibb.co/eRXtod"><img src="https://preview.ibb.co/gz7R8d/error.png" alt="error" border="0"></a>](url)

The console error is pointing to the same line as where @nicolas-saldarriaga described.
`this.geoFire = new GeoFire(this.dbRef.query.ref); `

**Comment by emannuell** [comment]
Same issue.
`ERROR Error: Uncaught (in promise): TypeError: geofire__WEBPACK_IMPORTED_MODULE_2__ is not a constructor
TypeError: geofire__WEBPACK_IMPORTED_MODULE_2__ is not a constructor`

**Comment by MichaelSolati** [comment]
For those of you who are having thus problem, it may be worth looking here... https://stackoverflow.com/a/51527285/5076023

**Comment by nfoote** [comment]
Thanks @MichaelSolati - that worked for me.

**Comment by CossyCossy** [comment]
@MichaelSolati - I tried this npm i firebase/geofire-js as you advised but instead the whole of my geofire got messed up

**Comment by MichaelSolati** [comment]
@CossyCossy there is a small chance in how important would take place. Instead of `import * as geofire from 'geofire'` your import would/should look like `import { Geofire } from 'geofire'`.

**Comment by jaufgang** [comment]
hmm...  I have installed the component from GitHub using `npm i firebase/geofire-js.`, and imported using `import {Geofire} from "geofire";`  but I still get the error.

```
main.js:11241 TypeError: geofire__WEBPACK_IMPORTED_MODULE_2__.Geofire is not a constructor
    at new GeoQuery (main.js:51)
```

**Comment by MichaelSolati** [comment]
@jaufang do you have a sample repo? (I don't mind helping!)

**Comment by jaufgang** [comment]
Thank you for your offer to help @MichaelSolati, but it turns out this was a false alarm.  The problem was that I am working in a monorepo with multiple `package.json` files and I had updated the dependecy in the wrong file.  As soon as I updated the dependency properly, it worked.  Thanks again!

**Comment by mmospanenko** [comment]
After 
`yarn add firebase/geofire-js`
I have 
`"geofire": "firebase/geofire-js",`
in my packages.json

and get a compilation error: Cannot find module 'geofire'.

I think I have to build geofire after clone (because there isn't dist directory in the geofire node_modules).

Any ideas how to integrate geofire in angular 6 project?

**Comment by MichaelSolati** [comment]
@mmospanenko you'll want to do a `npm install`, there's a `prepare` script that npm will run after installing it that will build it.

**Comment by mmospanenko** [comment]
@MichaelSolati thank you for an answer. I have (correct me if I'm wrong) to run npm install inside this folder (node_modules/geofire). Or my main install will build geofire?

Without building package manager can't recognize geofire as a module, maybe problem with index.js file (absent in root) or in package.js we have "main": "dist/index.cjs.js" (but we have only src directory). 
Can you check this moment, please?

**Comment by MichaelSolati** [comment]
A `npm i` in the root of your directory should do it. Mind you I'm not sure why yarn doesn't run the prepare script... After prepare is run, which runs build, then you should get your dist folder. (It not being in the root folder is not an issue)

**Comment by MichaelSolati** [comment]
P.S. for anyone who missed it, a module based version of geofire is up on npm. You can update to version 5.0.1 and be good to go!

**Comment by money2623** [comment]
> P.S. for anyone who missed it, a module based version of geofire is up on npm. You can update to version 5.0.1 and be good to go!

Hi @MichaelSolati 
I am still getting "GeoFire is not a constructor".
Can you help me with this?

**Comment by MichaelSolati** [comment]
@money2623 as it structured modularly you'll need to either import it as:
```
import { GeoFire } from 'geofire';

// OR

const { GeoFire } = require('geofire');

// OR

const GeoFire = require('geofire').Geofire;
```

**Comment by ziyaddin** [comment]
After import, you might need to use GeoFire via `GeoFire.GeoFire(firebaseRef)`, not `GeoFire(firebaseRef)` which causes `GeoFire is not a constructor` error.

**Comment by MichaelSolati** [comment]
You'll have to use `new`, so `const geofire = new GeoFire(firebaseRef)`.

**Comment by jQrgen** [comment]
```ts
const GeoFire = require('geofire').Geofire;
```

Is the only way to import i find working when using the following firebase.json.

This is because npm run build changes the first two imports but not the third.

```json
{
  "functions": {
    "source": "functions",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}

```

**Comment by ccynn** [comment]
I am not sure if this is the appropriate place to upload my issue, but it seems relevant within the context of the thread.

I too am receiving the "GeoFire is not constructor" error message.

I am trying to use geofire for a firebase cloud function.

My dependencies object within the package.json file includes...
`"geofire": "^5.0.1",`

At the top of my index.js file I have...
`const GeoFire = require('geofire');`

And within my actual cloud function I have...
`var geoFire = new GeoFire(geoFireRef);`

Any guidance would be appreciated as I am admittedly lost and could not resolve after having tried implementing above the solves..

**Comment by MichaelSolati** [comment]
If you guys create a lil repo or stackblitz sample I can definitely jump in and take a look at what's going on.

**Comment by ccynn** [comment]
> If you guys create a lil repo or stackblitz sample I can definitely jump in and take a look at what's going on.

I'm somewhat a beginner so what I did was attach the functions folder (excluding the node_modules folder because it was too big) as a reference point? Would this suffice?

[functionsGeoFire.zip](https://github.com/firebase/geofire-js/files/3115124/functionsGeoFire.zip)

**Comment by MichaelSolati** [comment]
@ccynn update line 7 of your `index.js` to:

```JavaScript
const GeoFire = require('geofire').GeoFire;
// Or
const { GeoFire } = require('geofire');
```

**Comment by ccynn** [comment]
> @ccynn update line 7 of your `index.js` to:
> 
> ```js
> const GeoFire = require('geofire').GeoFire;
> // Or
> const { GeoFire } = require('geofire');
> ```

Man...I swear I did this and I still got the error, but now it seems to work! Appreciate looking into this!
@MichaelSolati

**Comment by jQrgen** [comment]
This works in firebase functions with node 8:

```
// Import
const geofire = require('geofire');

// Usage
const geoFireInstance = new geofire.GeoFire(ref);
```

**Comment by puf** [comment]
This seems to have been addressed in the comments from @MichaelSolati and @jQrgen. If the situation can be improved by a change to this repo, without breaking it for users on other platforms, please open a PR against this issue.
