### ISSUE TITLE
GeoQueryDataEventListener issue

### ISSUE THREAD

**Issue by gauravbordoloi** [firebase/geofire-js#178]
Is there any callback similar to GeoQueryDataEventListener which is present in Java?

**Comment by puf** [comment]
From the [documentation](https://github.com/firebase/geofire-js#geofire-for-javascript---):

> To keep things simple, GeoFire stores data in its own format and its own location within your Firebase database.

This means that geofire-js keeps the geolocation data in a separate node from any other data about the objects.
