### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by ziyaddin** [firebase/geofire-js#180]
When is npm package `5.0.0` version going to be "officially" released (with `latest` tag)?

![image](https://user-images.githubusercontent.com/1016523/52182362-c66d8000-2815-11e9-8efe-10341b8cb8b2.png)

**Comment by Feiyang1** [comment]
Thanks for your patience. The latest package has been released in npm.

**Comment by ziyaddin** [comment]
Thanks!
