### ISSUE TITLE
Geofire.min.js not in CDN

### ISSUE THREAD

**Issue by suztomo** [firebase/geofire-js#181]
I'm trying to use Geofire in my hobby project. README's code did not work.

<img width="825" alt="screen shot 2019-03-03 at 20 49 20" src="https://user-images.githubusercontent.com/28604/53706049-5d6a2f80-3df6-11e9-8541-ad6acb5e6541.png">

### Version info

**Firebase:**
3.7.0

**GeoFire:**
5.0.1

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

Access https://cdn.firebase.com/libs/geofire/5.0.1/geofire.min.js in browser. 

### Steps to reproduce

Access https://cdn.firebase.com/libs/geofire/5.0.1/geofire.min.js in browser. 

### Expected behavior

Browser to show JavaScript file

### Actual behavior

Browser shows 404 error.

**Comment by MichaelSolati** [comment]
The url seems to work, maybe it just hadn't updated in time?

**Comment by suztomo** [comment]
Thank you. The URL works now.
