### ISSUE TITLE
Firebase radius issue

### ISSUE THREAD

**Issue by daniyal-intellicel** [firebase/geofire-js#184]
### Version info

**RN-Firebase: ^5.4.3**

**GeoFire: ^5.0.1**

### Steps to reproduce

I am using geofire with react native application, there are multiple nodes (location) present around the world in my db, and now I am fetching them using geoQuery in 100km radius, but if the fetched nodes are less than 50, the radius increase by 100km and so on. I figured if I use 20,000 km as Max_Radius then I'll cover the globe. But once my radius crossed 5400km I was only getting the nearest nodes, but where as I am getting all the nodes at 5400km, even those which are 12000km away from center. So I set the max at 5400km, but that differs with respect to center, like 5400km is max to C1, but 4000km is max to C2 and increasing that would result only near nodes.

### Expected behavior

Get all nodes as I increase the radius

### Actual behavior

Getting only nearest nodes at Max_Radius

**Comment by puf** [comment]
In my use of GeoFire and geohashes for queries I've seen them be fairly accurate, so I'm not sure what would cause this problem you're seeing. 

If the problem still persists, please provide the [minimum, complete/standalone code that we can run to reproduce the issue](http://stackoverflow.com/help/mcve).
