### ISSUE TITLE
Can't instantiate Geofire ref in TS

### ISSUE THREAD

**Issue by andriansergheev** [firebase/geofire-js#200]
This piece of code:

        var database = admin.database().ref()
            .child('geoData');
        var geoFireDB = new GeoFire.GeoFire(database)

Does not work.
Error:

Argument of type 'import("***").admin.database.Reference' is not assignable to parameter of type 'import("***").Reference'.
  The types of 'push(...).endAt(...).isEqual' are incompatible between these types.

Type '(other: import("***functions/node_modules/firebase-admin/lib/database").admin.database.Query | null) => boolean' is not assignable to type '(other: import("***/cloudFunctions/functions/node_modules/@firebase/database-types/index").Query | null) => boolean'.
      Types of parameters 'other' and 'other' are incompatible.
etc.

Here is what I have defined in package.json:
    "firebase": "^7.24.0",
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.11.0",
    "geofire": "^5.0.1",

Any ideas?

**Comment by ziyaddin** [comment]
Could you also show your import statement?

**Comment by andriansergheev** [comment]
import * as GeoFire from 'geofire';

Thanks!

**Comment by ziyaddin** [comment]
What about other imports? I am asking because I have tested your import statement and the piece of code and they do not cause error.

**Comment by ziyaddin** [comment]
Oh, I remembered. It happened to me too. The reason of error is that when GeoFire is being initialized, it requires `Reference` typed object **without** the `path` property but firebase-admin creates `Reference` typed object **with** the `path` property. Use the code below to fix the typing error:

var geoFireDB = new GeoFire.GeoFire(database as unknown as GeoFire.GeoFireTypes.firebase.Reference);

**Comment by ziyaddin** [comment]
@andriansergheev any success?

**Comment by andriansergheev** [comment]
Works. I'm coming from a strong-typed world and this kind of dances are incomprehensible for my brain,
Thanks again,

**Comment by ziyaddin** [comment]
You are welcome.
