### ISSUE TITLE
What to do when my project using Firebase version 9 but i need to use geofire

### ISSUE THREAD

**Issue by AliMohammad93** [firebase/geofire-js#237]
I'm using realtime database  javascript sdk v9 in all functions in my app and everything work perfect

I need to add geofire to store and retrieve locations with the ability retrieve location with a certain radius 

What is the best approach to deal with that?

Should i back to v8 to use geofire ?

**Comment by puf** [comment]
See https://github.com/firebase/geofire-js/issues/233
