### ISSUE TITLE
What is the recommended way of updating geolocation while preserving associated data?

### ISSUE THREAD

**Issue by stefek99** [firebase/geofire-js#40]
I have the following structure:

![screen shot 2014-08-27 at 00 02 03](https://cloud.githubusercontent.com/assets/249703/4053134/1d83a16c-2d75-11e4-9e05-3e1743316cc1.png)

I would like to update the location, while preserving the `data`

There is `GeoFire.set(key, location)` https://github.com/firebase/geofire-js#geofiresetkey-location

But when I call it the `data` would be lost.

I think I've found a workaround but it doesn't seem very intuitive to me:

```
        firebaseRef.child('data').once('value', function(snap) {
          var data = snap.val();
          geofire.set(name, [lat, long]).then(function() {
           firebaseRef.child('data').set(data);
          }, function(error) {
            console.log('Error: ' + error);
          });
        });
```
1. Saving data locally
2. Updating geofire
3. Storing data back to Firebase

Seem like a lot of work. Is there a better way?

Video explanation: https://www.youtube.com/watch?v=i5u77q7l8dU

You data sets are updating niceely: https://publicdata-transit.firebaseio.com/sf-muni :)

Thanks!

**Comment by santoshgistto** [comment]
so @jwngr what is the best way to load the additional data in list (android), ex: geofire returns 100 bars, are we need to make 100 calls?

**Comment by jwngr** [comment]
Yes, you should look them up individually by ID. This does require 100 calls, but since we use a websocket which has already established an HTTPS connection, it should be fast. It's not like you are making 100 HTTPS requests which are all opening connections to our server.

**Comment by santoshgistto** [comment]
got it thank you @jwngr

**Comment by jaufgang** [comment]
Thanks for the explanation.  As a new firebase/geofire user I found myself scratching my head reading the geofire docs trying to figure out how to make geotagged data searchable using geofire, until I found this issue referenced in a StackOverflow page

I think it would be very helpful if the above guidelines were to be included in the README.md.  It wasn't clear to me that "some_key" is meant to be a reference to an existing key of an object somewhere else in the db.  Perhaps expanding the "Example Usage" paragraph with some detail showing that there would be a separate /bars/<bar-id> for the bar data and /barLocations/<bar-id> for the geofire index would make this more clear.

**Comment by jwngr** [comment]
Thanks for the message @jaufgang. I actually have a blog post in flight that goes through a larger example but just haven't had enough time to finish it. I plan on adding it to the README once it is done. Hopefully that will make it more clear for everyone.

**Comment by benjaminmbrown** [comment]
This is a great way to do it. Currently I have a leaflet app that uses Geofire. This way I can quickly load marker loc data via Geofire . Then, when a user clicks the marker, they get the marker details, which reference another ref that has all the data. This keeps from grabbing too
Much data initially.
