### ISSUE TITLE
Error: Cannot find module 'vertx' from '/proj_directory/node_modules/geofire/node_modules/rsvp/dist'

### ISSUE THREAD

**Issue by leocristofani** [firebase/geofire-js#58]
I'm trying to use GeoFire with CommonJS and Browerify by I get this error whenever I require geofire in a module. I found this issue thread (https://github.com/tildeio/rsvp.js/pull/339) on GitHub for users of the library. Was wondering if the fix should be done from GeoFire codebase.

Thanks!

**Comment by jwngr** [comment]
Well that's interesting. It looks like this is an issue with RSVP (more details [here](https://github.com/tildeio/rsvp.js/issues/352)) and there is nothing we can do until they release a new version with their recent fix (aka the PR you linked to). That fix is already in their `master` branch, so as soon as they cut a 3.0.17 release, you can upgrade to that and your problem should be fixed.

**Comment by jwngr** [comment]
This is now fixed in GeoFire 3.2.2. See issue #62 for more details.
