### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ravivit9** [firebase/geofire-js#65]
I want to use [Sourcegraph](https://sourcegraph.com) for geofire-js code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/firebase/geofire-js. (It should only take 30 seconds.)

Thank you!

**Comment by jwngr** [comment]
Hey @ravivit9 - thanks for opening this issue. I had never heard of Sourcegraph before and I am a bit confused as to what value it provides. We tend to not sign up for these kinds of things as they just become one more thing to worry and think about. Can you explain what value this provides and how this will help you use the library?

**Comment by jwngr** [comment]
Closing. Feel free to give me a pitch for this if you think we should pursue it.
