### ISSUE TITLE
Example how to use Firebase Queries

### ISSUE THREAD

**Issue by ilionic** [firebase/geofire-js#66]
Based on Docs:
'With the release of GeoFire 3.1.0, this library now uses the new query functionality found in Firebase 2.0.0.'
In particular I am interested in `limitToLast` query found in Firebase with expected usage:
```
geoFireRef.limitToLast(2).on("key_entered", function(key, location, distance) { ...
```
But it throws an error `TypeError: geoFireRef.limitToLast is not a function`
Is it possible to use Firebase queries in GeoFire?

**Comment by jwngr** [comment]
That sentence in the docs refers to how GeoFire functions "under the hood," so to speak. GeoFire internally uses Firebase queries. It still doesn't have an API to limit to a certain number of results, although you can pretty easily get this functionality with little to no performance loss. Check out issues #59 for some ways to do that.
