### ISSUE TITLE
Question: Number of GeoIndices?

### ISSUE THREAD

**Issue by cskjoldborg** [firebase/geofire-js#70]
Great library!
Design question...(may be just as much Firebase as GeoFire related)
Would you consider it feasible to add hundreds of thousands of small geo indices?
I have use case where I have a user generated  item that needs to be tagged with geo locations. Sometimes it may be 5 sometimes 5000. There will be thousands of these user generated items per day and storing all their tags in a huge geoindex will require me to fetch way to may to the client only to filter most of them out.

**Comment by jwngr** [comment]
You should be able to create as many geo indices as you want. Each can go in its own node and that should scale perfectly fine. The big limiting factor will be how much data you transfer down clients. You will want to make sure you are not pulling down every geo index to a single client. If you limit it to just the geo index they care about, then you should be totally fine :+1:
