### ISSUE TITLE
Geofire once queries (key_entered)

### ISSUE THREAD

**Issue by mellinas** [firebase/geofire-js#79]
Hi,

As you ask about enhancements, I got another interesting use case.

In my app, I want to send Pushs notification to users in the x miles around.
So, I use a Geofire query with key_entered. 
But, I would like the query stop, once all the current child have been entered (like a .once() in Firebase). If new users come in the query, I don't want to send them a notification. 

I could use a Firebase .once event and compare distance, but if a query would exist for that, I think it should be better. 

What do you think? 

Cheers,
Clément

**Comment by puf** [comment]
Geofire fires a Ready event when it has finished loading initial data. Also
see: http://stackoverflow.com/a/33009089

**Comment by mellinas** [comment]
Ah great, I thought it means only the query was ready but I was afraid not all events were launched

Great, I close the issue :-)

Thanks
