### ISSUE TITLE
limit results

### ISSUE THREAD

**Issue by karlpower6** [firebase/geofire-js#83]
Is it possible to limit results for a specific query?
Similar to .limitToLast() in the Firebase API

**Comment by jwngr** [comment]
The answer slightly depends on what you are asking. If you want the `N` closest points, you should read the discussion in #59. If you want any `N` points (not the `N` closest) within your query, then you can do this by just having a variable which counts the number of keys that have entered and [turning off the query](https://github.com/firebase/geofire-js#geocallbackregistrationcancel) once the counter reaches `N`.

**Comment by karlpower6** [comment]
Thanks!

**Comment by vision-4** [comment]
the new [turning off the query](https://github.com/firebase/geofire-js/blob/master/docs/reference.md#geocallbackregistrationcancel) link
