### ISSUE TITLE
Allow setting of promise library

### ISSUE THREAD

**Issue by allenhartwig** [firebase/geofire-js#84]
It would be nice to support the setting of a desired promise library, such as Bluebird, to override the default RSVP lib. eg: `GeoFire.Promise = require('bluebird');`

**Comment by jwngr** [comment]
Yeah this is definitely a fair request. I actually don't like having to make people include a Promise library at all to be honest. I've considered just packaging `RSVP` into the source code or using a very basic Promise polyfill for old browsers which don't have the built-in `Promise`. In both of those cases, the promises would be transparent to the end developer and you don't have to include a new script tag / npm dependency. Do you think that is preferable or would you rather just have a configurable promise library? I'm a little undecided.

**Comment by rolandjitsu** [comment]
How about using the native ES6 [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) implementation? And let the user include something like [es6-promise](https://github.com/jakearchibald/es6-promise) or [es6-shim](https://github.com/paulmillr/es6-shim) that have polyfills for the native Promise (it's already implemented in most modern browsers). It would be a lot less intrusive and it would work well with other libs/frameworks that follow the same pattern (Angular 2 for instance).

Also, have you considered using [Observables](https://github.com/ReactiveX/RxJS)? It's a lot better when it comes to handling callbacks.

**Comment by rolandjitsu** [comment]
It's really not ideal that I have a promise lib and the native promise used together. And I cannot use geofire without RSVP. I could quickly make a PR that removes RSVP and uses the native promises + add docs on how to include the polyfill if support for older browsers is wanted.

**Comment by jwngr** [comment]
Thanks for the comments @rolandjitsu. I'd be interested in updating GeoFire to use the native `Promise` implementation and require a polyfill for older browsers. Even better would be packaging the polyfill into the library assuming it isn't too large.

As for observables, I have considered them. I went with an API that mimicked the Firebase API, which does not yet support observables. Maybe in the future we will add support for observables.

It would be great if you could take a crack and send me a PR!

**Comment by rolandjitsu** [comment]
Sounds great, I'd be happy to make the switch to native promises these days. And I think it's better to not package the polyfill as we would have to also keep track of the version updates for that polyfill + we would force the users to always use our version. Also, there might be libs that would also include the same polyfill and it would get ugly.

Yeah, I can see how not using Observables makes sense for now, but in the future, it might be a good idea to use it. When you think you might want to make the switch, I would be open to making a PR.

**Comment by jwngr** [comment]
Even better, I just put together https://github.com/firebase/geofire-js/pull/93 which removes the RSVP dependency entirely! Once it gets merged in, I'll cut a `4.0.0` release of GeoFire and close this issue.

**Comment by jwngr** [comment]
[GeoFire `4.0.0`](https://github.com/firebase/geofire-js/releases/tag/v4.0.0) has arrived and it has no promise library dependency at all! Enjoy!

**Comment by rolandjitsu** [comment]
Great :+1:
