### ISSUE TITLE
How to do complex queries with geofire?

### ISSUE THREAD

**Issue by capira12** [firebase/geofire-js#95]
I am trying to use GeoFire, but even after reading all the examples here https://github.com/firebase/geofire-js/tree/master/examples I don't quite understand how it works. 
with this snipped you can set a geo location for a single key:  
```
geoFire.set("some_key", [37.785326, -122.405696]).then(function() {
  console.log("Provided key has been added to GeoFire");
}, function(error) {
  console.log("Error: " + error);
});
```
but how do I use geo locations for complex objects instead of simple string keys? 
what if you have a restaurant with a name, average dish price and opening hours? do you need to store them in a second collection and somehow join them in your query?
I found this discussion https://github.com/firebase/geofire-js/issues/40 — it answers the question that you actually need to keep the geofire data in a seperate collection, but i am still wondering: 
how do you make more complex queries such as "near my location, open now and $15 avg dish price" ? do you really need to load all ids of locations nearby and then send those ids back to the server in a second query to filter out the ones that match the complex query? how do you do that? is there any example?

thanks a lot for your help!

**Comment by jwngr** [comment]
Also posted to the Firebase Google Group [here](https://groups.google.com/forum/#!msg/firebase-talk/AKj-bNa3igo/mA-VUIFHAAAJ). Gonna answer over there since that is a better forum for this kind of question.
