### ISSUE TITLE
The documentation is confusing

### ISSUE THREAD

**Issue by daveozoalor** [firebase/geofire-js#96]
How can i find list of posts made close to me or by users who are closest to me, for instance?

Here is how i setup my database:
1- users
*id
*email
*password
*longitude
*latitude

2- posts:
id
title
body
longitude
lattitude

How does geofire come in and what exact query do i write?

I have tried to implement geofire twice, all ending in failure because i dont understand the concept beyond the example in the docs

**Comment by jwngr** [comment]
Sorry for the confusion! Let's see if I can explain some of the high level points:

1. The first step is that you need to add things to a GeoFire index using `GeoFire.set()`. When a user moves or a new post is added, you should call [`GeoFire.set()`](https://github.com/firebase/geofire-js#geofiresetkeyorlocations-location) to add that user / post to your GeoFire index. I would actually suggest having two separate GeoFire indexes: one for users and one for posts.
2. Once your indexes are set up, you can create a [`GeoQuery`](https://github.com/firebase/geofire-js#geofirequeryquerycriteria) to query your index. If you want to find all posts that are close to you, you would create a query on your posts GeoFire index which is centered at your current latitude and longitude and with whatever radius you want.
3. To actually get notified when things enter your query, you would add an [`on("key_entered")`](https://github.com/firebase/geofire-js#geoqueryoneventtype-callback) listener to your query. This will fire for every post that matches your query. In the callback to this method, you can do whatever you want (e.g. add it to an array or append it to the DOM).

Hope that helps.

**Comment by daveozoalor** [comment]
Thanks a lot. Can you please give a sample query to retrieve what I asked
for?
I am totally lost in that. Just need to get an idea.

**Comment by jwngr** [comment]
Sure, he is an example query you could do assuming you've created a GeoFire index at the `/_geofirePosts` node:

```
var rootRef = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
var postsRef = rootRef.child("posts");
var geofirePostsRef = rootRef.child("_geofirePosts");

var geoFire = new GeoFire(geofirePostsRef);

var geoQuery = geoFire.query({
  center: [10.38, 2.41],
  radius: 10.5
});

geoQuery.on("key_entered", function(key, location, distance) {
  // Look up the post by key
  postsRef.child(key).once("value", function(snapshot) {
    var post = snapshot.val();
    // do something with the post
  });
});
```

It may also be helpful to check out all of the [examples](https://github.com/firebase/geofire-js/tree/master/examples).
