### ISSUE TITLE
Typescript Definition File

### ISSUE THREAD

**Issue by increos** [firebase/geofire-js#98]
Are there plans for a typescript definition file for use in Angular 2

**Comment by jwngr** [comment]
No plans, but we welcome contributions from the community and will review a PR if you want to give it a shot.

**Comment by Lindstrom1989** [comment]
Would really like to see this!

**Comment by tgensol** [comment]
+1

**Comment by maxmumford** [comment]
+1

**Comment by jwngr** [comment]
See https://github.com/firebase/geofire-js/issues/116 for some workarounds.

Please avoid "+1"s and "me too"s since they don't add to the conversation. Instead, use the GitHub reaction emojis or, better yet, send a PR.

**Comment by bijoutrouvaille** [comment]
Had to write one for myself; here's the gist. https://gist.github.com/bijoutrouvaille/4b03c725a2c9cc2d5b08a833dba9523c

**Comment by jaufgang** [comment]
@jwngr , could @bijoutrouvaille 's `geofire.d.ts` file be added to the distribution?  It would be very helpful for typescrript/angular 2+ developers.  
Thanks.
